package kr.co.architecture.core.ui.preview

import androidx.compose.ui.tooling.preview.PreviewParameterProvider
import kr.co.architecture.core.ui.BaseCenterDialogUiModel
import kr.co.architecture.core.ui.util.UiText

class BaseDialogUiModelPreviewParam : PreviewParameterProvider<BaseCenterDialogUiModel> {
  override val values: Sequence<BaseCenterDialogUiModel> = sequenceOf(
    BaseCenterDialogUiModel(
      titleMessage = UiText.PlainText("titleMessage"),
      contentMessage = UiText.PlainText("contentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessagecontentMessage"),
      confirmButtonMessage = UiText.PlainText("confirmButtonMessage")
    ),
    BaseCenterDialogUiModel(
      titleMessage = UiText.PlainText("titleMessage"),
      contentMessage = UiText.PlainText("contentMessage"),
      confirmButtonMessage = UiText.PlainText("confirmButtonMessage")
    )
  )
}
