[versions]
# libraries
androidxCore = "1.12.0"
androidxLlifecycleRuntimeKtx = "2.7.0"
androidxActivityCompose = "1.8.2"
androidxComposeBom = "2025.04.00"
androidxNavigation = "2.7.7"
androidxHiltNavigationCompose = "1.2.0"
androidxNavigationCommonKtx = "2.7.7"
junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
orgMockitoKotlin = "4.1.0"
mock = "5.5.0"
androidxEspresso = "3.5.0"
androidxLifecycleViewmodelCompose = "2.7.0"
androidxLifecycleRuntimeCompose = "2.7.0"
composeMaterial = "1.7.0-alpha06"
androidxComposeMaterial3 = "1.2.0"
ioCoilKtCompose = "2.6.0"
kotlinxSerializationJson = "1.5.1"
okhttpLogging = "4.12.0"
retrofit = "2.11.0"
androidxDataStore = "1.0.0"
room = "2.6.1"
workManager = "2.9.0"
hiltWorker = "1.2.0"
protobuf = "4.26.1"
gson = "2.10.1"
serializationLibVer = "1.6.3"
sandwitch = "2.0.8"
kotlinxCoroutines = "1.8.0"
androidxTestRules = "1.5.0"
immutableCollectionVer = "0.3.7"
coroutineVersion = "1.8.0"
glide = "1.0.0-beta01"
lottie = "6.0.0"

# plugins
protobufPlugin = "0.9.4"
androidGradlePlugin = "8.6.0"
jetbrainsKotlin = "2.0.0"
serializationPluginVer = "1.7.10"

# libraries and plugins
daggerHilt = "2.52"
material = "1.11.0"
ksp = "2.0.0-1.0.21"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
androidx-compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "androidxComposeMaterial3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-navigation-common-ktx = { group = "androidx.navigation", name = "navigation-common", version.ref = "androidxNavigationCommonKtx"}
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "daggerHilt" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit"}
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
org-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "orgMockitoKotlin" }
org-mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mock" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycleViewmodelCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycleRuntimeCompose" }
io-coil-kt = { group = "io.coil-kt", name = "coil-compose", version.ref = "ioCoilKtCompose" }
com-google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
com-google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLogging" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson",version.ref = "retrofit" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager"}
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorker" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
com-google-code-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}
org-jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationLibVer" }
org-jetbrains-kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollectionVer"}
org-jetbrains-kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutineVersion"}
org-jetbrains-kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutineVersion"}
com-github-skydoves-sandwich = { group = "com.github.skydoves", name = "sandwich", version.ref = "sandwitch" }
com-github-skydoves-sandwich-retrofit = { group = "com.github.skydoves", name = "sandwich-retrofit", version.ref = "sandwitch" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
com-github-bumptech-glide = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glide" }
com-airbnb-android-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
org-jetbrains-kotlin-plugin-serialization = { id ="org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPluginVer" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrainsKotlin" }

# Plugins defined by this project
architecture-sample-ui = { id = "architecture.sample.ui", version = "unspecified"  }
architecture-sample-base-setting = { id = "architecture.sample.base.setting", version = "unspecified"  }

[bundles]
[metadata]
